---
- hosts: localhost
  tasks:
    - name: 'Install packages'
      become: yes
      package:
        name: "{{ item }}"
        state: 'present'
      with_items:
        - koji
        - tito
        - vagrant
