---
- hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - debug:
        msg: "{{ current_directory }}"

    - name: 'Clone git repository'
      command: "git clone https://{{ gitlab_server }}/{{ repo }}"
      args:
        chdir: "{{ current_directory }}"

    - name: 'Add my remote'
      command: "git remote add ehelms git@{{ gitlab_server }}:ehelms/{{ repo.split('/')[1] }}"
      args:
        chdir: "{{ current_directory }}/{{ repo.split('/')[1] }}"
